/**
 * Stable error codes.
 *
 * These are the machine-readable half of an error response; the human-readable
 * half is the message. Clients branch on the code, never on the message text.
 */
export const ERROR_CODES = {
  // Auth
  UNAUTHENTICATED: "UNAUTHENTICATED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  SESSION_REVOKED: "SESSION_REVOKED",
  FORBIDDEN: "FORBIDDEN",

  // Tenancy
  ORGANIZATION_MISMATCH: "ORGANIZATION_MISMATCH",
  NO_ORGANIZATION_MEMBERSHIP: "NO_ORGANIZATION_MEMBERSHIP",

  // Generic resource lifecycle
  NOT_FOUND: "NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  CONFLICT: "CONFLICT",

  // Domain
  CARDINALITY_VIOLATION: "CARDINALITY_VIOLATION",
  INVALID_EFFECTIVE_RANGE: "INVALID_EFFECTIVE_RANGE",
  INVALID_RULE_CONDITIONS: "INVALID_RULE_CONDITIONS",
  MANUAL_RULE_REQUIRES_EMPLOYEE: "MANUAL_RULE_REQUIRES_EMPLOYEE",

  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
